version: '3.3'
services:
  db:
    container_name: imagine-postgres
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

  db-admin:
    container_name: imagine-pgAdmin
    image: dpage/pgadmin4
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DEFAULT_PASSWORD=postgres
      - POSTGRES_DEFAULT_EMAIL=ben.lacey@mrzen.com
      - POSTGRES_LISTEN_PORT=80
      -
    ports:
      - '5050:80'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local